name: Checkout main into QA branch

on: 
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  checkout-main_into_qa:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git config pull.rebase true
    - name: Dump GitHub events
      env:
        GITHUB_EVENTS: ${{ toJson(github.event) }}
      run: |
        echo "$GITHUB_EVENTS"
    - name: Delete and recreate QA branch using main
      run: |
        git checkout main
        git pull
        git push origin --delete qa
        git checkout -b qa
        git push -u origin qa